# Ansible Playbook for qqq
- name: Execute qqq Playbook (postgresql)
  hosts: all
  gather_facts: yes
  tasks:
    - name: Verify database engine connectivity
      debug:
        msg: "Running playbook test.yml on {{ inventory_hostname }}"
